services:

  nginx:
    image: nginx
    environment:
      - VIRTUAL_HOST=site.local
    container_name: nginx
    depends_on:
      - php
      - mysql
    ports:
      - "80:80"  
    volumes:
      - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
      - ./html/:/var/www/html/
    networks:
      - frontend
      - backend

  php:
    build:
      context: ./docker/php
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    container_name: php
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./html/:/var/www/html/
    ports:
          - "9000:9000"
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped   
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: always
    ports:
      - 8081:80
    networks:
      - frontend
      - backend


networks:
  frontend:
    external:
      name: proxy_proxy
  backend: